spring.application.name=incidencias-api

spring.datasource.url=jdbc:postgresql://localhost:5432/incidencias_db
spring.datasource.username=postgres
spring.datasource.password=6272

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.data.redis.host=localhost
spring.data.redis.port=6379

server.port=8083

spring.jackson.serialization.write-dates-as-timestamps=false